name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          ssh-key: ''
          ssh-strict: ''
          dotnet-version: '3.1.x'
      - name: Run Powershell script   
        shell: powershell
        run: C:\Users\mshaik07\Desktop\windows-service-deployment.ps1
    #  - name: Build 
        #run: dotnet build --no-restore
      - name: Copy executable
        shell: powershell
        run: Copy-Item -Path "C:\actions-runner\_work\SampleWindowsService\SampleWindowsService\bin\Debug\SampleWindowsService.exe" -Destination "C:\Users\mshaik07\source\repos\SampleWindowsService\bin\Debug" -Recurse -force
     
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
