name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.0.x'
      - name: Run Powershell script   
        shell: powershell
        run: C:\Users\mshaik07\Desktop\windows-service-deployment.ps1
      #- powershell: C:\Users\mshaik07\Desktop\windows-service-deployment.ps1
      # - name: Restore dependencies
      #   run: dotnet restore
      # - name: Build
      #   run: dotnet build --no-restore
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
