name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          ssh-key: ''
          ssh-strict: ''
          dotnet-version: '3.1.x'
      - name: Run Powershell script   
        shell: powershell
        run: C:\ArchitectureServices\windows-service-deployment.ps1

 
